name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# TODO: There are breaking changes in dagger; once things stabilize, this needs to be updated.
jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Run lints
        # See all options at https://github.com/dagger/dagger-for-github
        uses: dagger/dagger-for-github@v3
        with:
          # renovate: datasource=github-releases depName=dagger/dagger versioning=semver-coerced
          version: 0.2.36
          cmds: do lint
